<a href="https://colab.research.google.com/github/Gowtham070822/sirpi/blob/main/exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/data analytics folder/Automobile.csv')

In [6]:
df.head(10)

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   
5          2                161         audi       gas        std   
6          1                158         audi       gas        std   
7          1                168         audi       gas        std   
8          1                158         audi       gas      turbo   
9          2                192          bmw       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   
5             two        sedan          fwd           front        99.8  ...   
6            four        sedan          fwd           front       105.8  ...   
7            four        wagon          fwd           front       105.8  ...   
8            four        sedan          fwd           front       105.8  ...   
9             two        sedan          rwd           front       101.2  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   
5          136         mpfi  3.19    3.40               8.5        110   
6          136         mpfi  3.19    3.40               8.5        110   
7          136         mpfi  3.19    3.40               8.5        110   
8          131         mpfi  3.13    3.40               8.3        140   
9          108         mpfi  3.50    2.80               8.8        101   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  
5      5500       19           25  15250  
6      5500       19           25  17710  
7      5500       19           25  18920  
8      5500       17           20  23875  
9      5800       23           29  16430  

[10 rows x 26 columns]

In [ ]:
df.tail()

symboling  normalized_losses   make fuel_type aspiration number_of_doors  \
196         -1                 95  volvo       gas        std            four   
197         -1                 95  volvo       gas      turbo            four   
198         -1                 95  volvo       gas        std            four   
199         -1                 95  volvo    diesel      turbo            four   
200         -1                 95  volvo       gas      turbo            four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
196      sedan          rwd           front       109.1  ...          141   
197      sedan          rwd           front       109.1  ...          141   
198      sedan          rwd           front       109.1  ...          173   
199      sedan          rwd           front       109.1  ...          145   
200      sedan          rwd           front       109.1  ...          141   

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
196         mpfi  3.78    3.15               9.5        114      5400   
197         mpfi  3.78    3.15               8.7        160      5300   
198         mpfi  3.58    2.87               8.8        134      5500   
199          idi  3.01    3.40              23.0        106      4800   
200         mpfi  3.78    3.15               9.5        114      5400   

    city_mpg  highway_mpg  price  
196       23           28  16845  
197       19           25  19045  
198       18           23  21485  
199       26           27  22470  
200       19           25  22625  

[5 rows x 26 columns]

In [ ]:
df.shape

(201, 26)

In [ ]:
df.shape[0]

201

In [ ]:
df.shape[1]

26

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

In [ ]:
df.isnull().sum()

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [ ]:
df.nunique()

symboling                6
normalized_losses       58
make                    22
fuel_type                2
aspiration               2
number_of_doors          2
body_style               5
drive_wheels             3
engine_location          2
wheel_base              52
length                  73
width                   43
height                  49
curb_weight            169
engine_type              6
number_of_cylinders      7
engine_size             43
fuel_system              8
bore                    39
stroke                  36
compression_ratio       32
horsepower              58
peak_rpm                22
city_mpg                29
highway_mpg             30
price                  186
dtype: int64

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [ ]:
df.loc[0:10,"width":"bore"]

width  height  curb_weight engine_type number_of_cylinders  engine_size  \
0    64.1    48.8         2548        dohc                four          130   
1    64.1    48.8         2548        dohc                four          130   
2    65.5    52.4         2823        ohcv                 six          152   
3    66.2    54.3         2337         ohc                four          109   
4    66.4    54.3         2824         ohc                five          136   
5    66.3    53.1         2507         ohc                five          136   
6    71.4    55.7         2844         ohc                five          136   
7    71.4    55.7         2954         ohc                five          136   
8    71.4    55.9         3086         ohc                five          131   
9    64.8    54.3         2395         ohc                four          108   
10   64.8    54.3         2395         ohc                four          108   

   fuel_system  bore  
0         mpfi  3.47  
1         mpfi  3.47  
2         mpfi  2.68  
3         mpfi  3.19  
4         mpfi  3.19  
5         mpfi  3.19  
6         mpfi  3.19  
7         mpfi  3.19  
8         mpfi  3.13  
9         mpfi  3.50  
10        mpfi  3.50

In [ ]:
df.iloc[0:10,13:18]

curb_weight engine_type number_of_cylinders  engine_size fuel_system
0         2548        dohc                four          130        mpfi
1         2548        dohc                four          130        mpfi
2         2823        ohcv                 six          152        mpfi
3         2337         ohc                four          109        mpfi
4         2824         ohc                five          136        mpfi
5         2507         ohc                five          136        mpfi
6         2844         ohc                five          136        mpfi
7         2954         ohc                five          136        mpfi
8         3086         ohc                five          131        mpfi
9         2395         ohc                four          108        mpfi

In [ ]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [ ]:
df.shape


(201, 26)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

In [ ]:
df['engine_type'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf'], dtype=object)

In [ ]:
df['horsepower']

0      111
1      111
2      154
3      102
4      115
      ... 
196    114
197    160
198    134
199    106
200    114
Name: horsepower, Length: 201, dtype: int64

In [ ]:
df['city_mpg'].mean()

np.float64(25.17910447761194)

In [ ]:
df['highway_mpg'].mean()

np.float64(30.686567164179106)

In [ ]:
a=df['city_mpg'].mean()
b=df['highway_mpg'].mean()
if(a>b):
    print("city_mpg is better")
else:
    print("highway_mpg is better")


highway_mpg is better


In [ ]:
("city_mpg is better")if(a>b) else ("highway_mpg is better")

'highway_mpg is better'

In [ ]:
("city mpg is better")if(df['city_mpg'].mean()>df['highway_mpg'].mean())else("highway mpg is better")

'highway mpg is better'

In [ ]:
a=df['make'].value_counts().min()

In [ ]:
df

In [ ]:
df['make'].min()

'alfa-romero'

In [ ]:
df['make'].max()

'volvo'

2. Accessing Data with .loc[]
Using the following DataFrame:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Task
Retrieve the row where Name == "Charlie" using .loc[].
Select only the Age and Score columns for "Alice" and "Bob" using .loc[].

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["alice","bob","charlie","david"],
    "age":[24,27,22,32],
    "score":[85,90,78,88]
})
print(df)

      name  age  score
0    alice   24     85
1      bob   27     90
2  charlie   22     78
3    david   32     88


In [ ]:
print(df.loc[2,"name":"age"])

name    charlie
age          22
Name: 2, dtype: object


In [ ]:
print(df.loc[1,"name":"age"])

name    bob
age      27
Name: 1, dtype: object


In [ ]:
print(df.iloc[1])

name     bob
age       27
score     90
Name: 1, dtype: object


In [ ]:
print(df.iloc[-2:])

    name  age  score
0  alice   24     85
1    bob   27     90


In [ ]:
df=pd.DataFrame({
    "Employee":["john","alice","bob","david"],
    "salary":[50000,60000,55000,65000],
    "department":["it","hr","it","finance"]
})

print(df[df['department']=="it"])
print(df[df['salary']>55000])

  Employee  salary department
0     john   50000         it
2      bob   55000         it
  Employee  salary department
1    alice   60000         hr
3    david   65000    finance


Using the following DataFrame:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
Task
Write a function that:
Converts marks below 50 to "Fail", and 50 or above to "Pass".
Apply this function to the "Marks" column and create a new column "Result".

In [ ]:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
df['result']=(df["Marks"]>=50).replace({True:"pass",False:"fail"})
print(df)



  Student  Marks result
0       A     45   fail
1       B     78   pass
2       C     62   pass
3       D     90   pass


Create a NumPy array with values from 1 to 12.
Reshape it into a 3x4 matrix.

In [ ]:
import numpy as np
arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You are given the following NumPy arrays:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
Task
Perform:
1.Element-wise multiplication of a and b.
2.Add 5 to each element of a using broadcasting.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a*b)
a=a+5
b=b+5
print(a)
print(b)

[10 40 90]
[6 7 8] [15 25 35]


Given:
arr = np.array([[3, 7, 2], [4, 9, 6]])
Task
Find the maximum value in the entire array.
Find the minimum value in each row.

In [ ]:
arr = np.array([[3, 7, 2], [4, 9, 6]])
print(np.max(arr[0]))
print(np.min(arr))

7
2


You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Task
Write a Pandas command to:
Group the DataFrame by "Department" and calculate the average salary per department.

In [ ]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
print(df.groupby("Department")["Salary"].mean())

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


Given the following DataFrame:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
Task
Sort the DataFrame by Population in descending order.

In [ ]:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
print(df.sort_values("Population",ascending=False))


          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


You are given the following DataFrame:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
Task
Retrieve the sales value for City A in the South Region using multi-indexing.

In [ ]:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
print(data,sep="")

{'Region': ['North', 'North', 'South', 'South', 'East', 'East'], 'City': ['A', 'B', 'A', 'B', 'A', 'B'], 'Sales': [200, 150, 180, 220, 300, 250]}


In [ ]:
print(df.loc[('South','A'),"Sales"])

180


reating a DataFrame from a NumPy Array
Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].

In [ ]:
import numpy as np
c=np.random.randint(10,100,size=(5,4))
df=pd.DataFrame(c,columns=(["A","B","C","D"]))
print(df)

    A   B   C   D
0  20  49  62  35
1  59  69  28  20
2  78  93  90  10
3  76  86  99  73
4  89  81  95  53


13. Conditional Column Update
Given the following DataFrame:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
Task
Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.

In [ ]:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
df.loc[df["Attendance"]<60,"Marks"]=0
df

Student  Marks  Attendance
0    Alice     88          85
1      Bob     45          50
2  Charlie     76          90
3    David     90          60

14. Advanced Filtering
From a CSV file "employees.csv" with columns:
EmployeeID, Department, Salary, Experience (in years).
Note: You should create “employees.csv” & perform the below task
Task
Write a Pandas query to:
Select employees from "IT" or "Finance" department
Having Salary > 60,000
AND at least 5 years of experience

In [ ]:
import pandas as pd
data={
    "employeeID":[1,2,3,4,5,6,7],
    "Department":["IT","HR","Finance","IT","HR","Finance","IT"],
    "Salary":[70000,62000,65000,80000,50000,75000,62000],
    "Experience":[6,4,5,7,3,8,5]
}
df=pd.DataFrame(data)
df.to_csv("employees.csv",index=False)
df


employeeID Department  Salary  Experience
0           1         IT   70000           6
1           2         HR   62000           4
2           3    Finance   65000           5
3           4         IT   80000           7
4           5         HR   50000           3
5           6    Finance   75000           8
6           7         IT   62000           5

In [ ]:
df=pd.read_csv("employees.csv")
print(df[df["Department"].isin(["IT","Finance"])])


   employeeID Department  Salary  Experience
0           1         IT   70000           6
2           3    Finance   65000           5
3           4         IT   80000           7
5           6    Finance   75000           8
6           7         IT   62000           5


In [ ]:
print("salary grater then of 60000 in thousand")
print(df[df["Salary"]>60000])

salary grater then of 60000 in thousand
   employeeID Department  Salary  Experience
0           1         IT   70000           6
1           2         HR   62000           4
2           3    Finance   65000           5
3           4         IT   80000           7
5           6    Finance   75000           8
6           7         IT   62000           5


In [ ]:
print(df[df["Experience"]>=5])
print("atlest 5 years of experience")


   employeeID Department  Salary  Experience
0           1         IT   70000           6
2           3    Finance   65000           5
3           4         IT   80000           7
5           6    Finance   75000           8
6           7         IT   62000           5
atlest 5 years of experience


15. Grouping & Aggregation with Multiple Conditions
Given the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
Task
Find the average salary for each department, but only for employees with at least 5 years of experience.

In [ ]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
df

Department  Salary  Experience
0         IT   70000           5
1         HR   50000           4
2         IT   80000           7
3    Finance   60000           3
4         HR   52000           2
5    Finance   72000           8
6         IT   65000           6

In [ ]:
df=df[df["Experience"]>=5]
print(df)
print(df.groupby(["Department"])["Salary"].mean())

  Department  Salary  Experience
0         IT   70000           5
2         IT   80000           7
5    Finance   72000           8
6         IT   65000           6
Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


16. NumPy - Complex Indexing
Create a 5x5 NumPy array with random values between 1 and 100.
Write a NumPy command to:
Extract only even numbers from the array.
Extract values from the last row and last column.
Replace all values greater than 50 with 0.

In [ ]:
import numpy as np
arr=np.random.randint(1,101,size=(5,5))
print(arr)

[[54 21 43  6 71]
 [90 63 18 85 21]
 [13 51 27 37 30]
 [31 54 61 39 32]
 [ 8 70 18 13 38]]


In [ ]:
print("Extract only even numbers from the array.")
print(arr[arr%2==0])
print("even num of the array")

Extract only even numbers from the array.
[100  80  84  64  30  64  14  14  82  16]
even num of the array


In [ ]:
print("Extract values from the last row and last column.")
print(arr[-1,:])
print(arr[:,-1])

Extract values from the last row and last column.
[93 99 27 16  5]
[80 97 71 82  5]


In [ ]:
arr[arr>50]=0
print(arr)

[[ 0  0  0 29  0]
 [ 0  0  0 30  0]
 [15 47  0 47  0]
 [ 1 33 14 14  0]
 [ 0  0 27 16  5]]


17. Matrix Multiplication
Given the two NumPy matrices:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
Task
Perform matrix multiplication and output the result.

In [ ]:
import numpy as np
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
print(A*B)

[[ 2 12]
 [30 56]]


18. Finding Unique & Common Elements
You are given two NumPy arrays:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
Task
Find the elements that are common in both arrays.
Find the elements that are only present in arr1 but not in arr2.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])00
arr2 = np.array([30, 40, 70, 80, 90])
print("Find the elements that are common in both arrays:")
print(np.intersect1d(arr1,arr2))
print("Find the elements that are only present in arr1 but not in arr2:")
print(np.setdiff1d(arr1,arr2))

Find the elements that are common in both arrays:
[30 40]
Find the elements that are only present in arr1 but not in arr2:
[10 20 50 60]


19. Sorting & Ranking in Pandas
You are given the following DataFrame:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
Task
Sort the players by descending Score.
Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers.

In [ ]:

df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
df=df.sort_values("Score",ascending=False)
df["rank"]=range(1,5)
print(df.sort_index())

  Player  Score  rank
0      A    200     3
1      B    450     1
2      C    300     2
3      D    150     4


20. Optimizing Pandas Performance
You have a large CSV file ("big_data.csv") with 1 million rows.
Note: You should search & download a large csv file from any portal & use it to perform below tasks
Task
Write optimized Pandas code to:
Load only specific columns: "CustomerID" and "PurchaseAmount".
Load only the first 100,000 rows.
Use an efficient data type for "CustomerID" to save memory.


In [7]:
df=pd.read_csv("/content/drive/MyDrive/data analytics folder/Enterprice_servey.csv")


In [9]:
df.head()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries   
1  2023                     Level 1                99999       All industries   
2  2023                     Level 1                99999       All industries   
3  2023                     Level 1                99999       All industries   
4  2023                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...